export const conteudoCyber = {
    "prim-title": "Cyber Security",
    "prim-subtitle": "O que é Cybersecurity?",
    "prim-para-one": "Cybersecurity é como um escudo mágico que protege você e seus dados na Internet! Quando usamos a Internet para conversar, estudar ou brincar, deixamos pistas, como senhas, fotos ou mensagens. A cibersegurança ajuda a proteger essas pistas para que ninguém as use de forma errada.",
    "prim-para-two": "Imagine que você tem um tesouro. Você usaria um cadeado para proteger, certo? Na Internet, usamos ferramentas como senhas fortes, antivírus e até programas que funcionam como guardas de segurança para proteger nossos 'tesouros digitais'.",
    "prim-para-three": "Ser um bom defensor da cibersegurança significa não clicar em links suspeitos, não compartilhar informações pessoais com estranhos e sempre pedir ajuda de um adulto quando estiver em dúvida.",
    "prim-para-four": "Com essas dicas, você pode navegar na Internet com mais segurança e tranquilidade!",
    "prim-para-five": "",
    "prim-para-six": "",
    "prim-para-seven": "",
    "prim-para-eight": "",

    "sec-title": "Cyber Security",
    "sec-subtitle": "Entendendo Cybersecurity: Protegendo o Mundo Digital",
    "sec-para-one": "A cybersecurity, ou cibersegurança, é o conjunto de práticas e tecnologias usadas para proteger sistemas, redes e dados contra ataques ou acessos indesejados. Em um mundo cada vez mais conectado, onde compartilhamos informações pessoais, trabalhamos online e realizamos transações digitais, a cibersegurança se torna essencial para garantir a privacidade e a segurança de todos.",
    "sec-para-two": "",
    "sec-para-three": "Por que a cibersegurança é importante?",
    "sec-para-four": "Com o avanço da tecnologia, surgiram também novas ameaças, como vírus, hackers e golpes online. Esses riscos podem comprometer informações sensíveis, como senhas, documentos importantes e até dados financeiros. Sem medidas de proteção, ficamos vulneráveis a perdas e danos que podem ser difíceis de recuperar.",
    "sec-para-five": "",
    "sec-para-six": "",
    "sec-para-seven": "",
    "sec-para-eight": "",

    "terc-title": "Cyber Security",
    "terc-subtitle": "Principais áreas da cibersegurança",
    "terc-para-one": "Proteção de Dados: Evitar que informações pessoais ou empresariais sejam acessadas sem permissão.",
    "terc-para-two": "Segurança de Rede: Proteger redes de computadores contra ataques que possam roubar informações ou causar danos.",
    "terc-para-three": "Segurança de Aplicações: Garantir que programas e aplicativos sejam desenvolvidos de forma segura, sem brechas que possam ser exploradas.",
    "terc-para-four": "Educação dos Usuários: Ensinar boas práticas de segurança, como usar senhas fortes e reconhecer tentativas de phishing (golpes digitais).",
    "terc-para-five": "",
    "terc-para-six": "",
    "terc-para-seven": "",
    "terc-para-eight": "",

    "four-title": "Cyber Security",
    "four-subtitle": "Como podemos nos proteger?",
    "four-para-one": "Use senhas fortes e diferentes para cada conta.",
    "four-para-two": "Atualize sempre seus programas e dispositivos para corrigir falhas de segurança.",
    "four-para-three": "Desconfie de e-mails ou mensagens de desconhecidos pedindo informações pessoais.",
    "four-para-four": "Use antivírus e firewalls para proteger seus dispositivos.",
    "four-para-five": "Evite clicar em links ou baixar arquivos de fontes desconhecidas.",
    "four-para-six": "",
    "four-para-seven": "A cibersegurança é para todos",
    "four-para-eight": "Proteger-se no mundo digital não é apenas responsabilidade de grandes empresas ou especialistas. Cada um de nós, ao adotar boas práticas e estar atento aos riscos, contribui para um ambiente online mais seguro."
};

export const conteudoInternet = {
    "prim-title": "Internet",
    "prim-subtitle": "O que é a Internet?",
    "prim-para-one": "A Internet é como uma grande teia invisível que conecta computadores e pessoas no mundo inteiro! Com ela, você pode falar com amigos que moram longe, assistir vídeos, jogar seus jogos favoritos e aprender coisas novas.",
    "prim-para-two": "Pense na Internet como uma superestrada onde mensagens, fotos, vídeos e até músicas viajam bem rápido, chegando até você em segundos. Mas, para usar essa 'estrada digital', precisamos de aparelhos como computadores, tablets ou celulares e de algo chamado 'rede'.",
    "prim-para-three": "E sabe o que é importante? Usar a Internet com sabedoria! Ela é cheia de coisas legais, mas também tem armadilhas. Por isso, aprender a navegar com segurança é essencial.",
    "prim-para-four": "Pronto para explorar esse mundo mágico e cheio de possibilidades?",
    "prim-para-five": "",
    "prim-para-six": "",
    "prim-para-seven": "A Internet é uma rede gigantesca que conecta computadores, celulares e outros dispositivos do mundo inteiro. É como uma estrada digital que permite enviar e receber informações, como mensagens, vídeos, fotos e músicas, de forma rápida e fácil.",
    "prim-para-eight": "",

    "sec-title": "Internet",
    "sec-subtitle": "Como a Internet funciona?",
    "sec-para-one": "",
    "sec-para-two": "A Internet é formada por muitas redes menores conectadas entre si. Quando você faz uma pesquisa ou envia uma mensagem, essas informações viajam por cabos, antenas e satélites até chegarem ao destino. Esse processo acontece em segundos, parecendo quase mágico!",
    "sec-para-three": "",
    "sec-para-four": "",
    "sec-para-five": "",
    "sec-para-six": "",
    "sec-para-seven": "",
    "sec-para-eight": "",

    "terc-title": "Internet",
    "terc-subtitle": "O que podemos fazer na Internet?",
    "terc-para-one": "A Internet abriu um mundo de possibilidades. Veja algumas coisas incríveis que podemos fazer:",
    "terc-para-two": "Aprender: Assistir a aulas online, ler artigos e descobrir coisas novas.",
    "terc-para-three": "Comunicar: Conversar com pessoas de qualquer lugar do mundo.",
    "terc-para-four": "Entreter: Assistir a filmes, ouvir músicas e jogar jogos.",
    "terc-para-five": "Trabalhar e Criar: Fazer reuniões, criar projetos e compartilhar ideias.",
    "terc-para-six": "",
    "terc-para-seven": "",
    "terc-para-eight": "",

    "four-title": "Internet",
    "four-subtitle": "Como usar a Internet com segurança?",
    "four-para-one": "Embora a Internet ofereça muitas coisas boas, também é importante usá-la com cuidado. Aqui estão algumas dicas para navegar com segurança:",
    "four-para-two": "Proteja seus dados: Nunca compartilhe senhas ou informações pessoais com desconhecidos.",
    "four-para-three": "Evite links suspeitos: Não clique em mensagens ou sites que pareçam estranhos.",
    "four-para-four": "Converse com um adulto: Sempre peça ajuda se algo parecer errado ou se você tiver dúvidas.",
    "four-para-five": "Limite o tempo de uso: A Internet é ótima, mas é importante também aproveitar o mundo fora dela!",
    "four-para-six": "",
    "four-para-seven": "O futuro da Internet",
    "four-para-eight": "A cada dia, novas tecnologias estão transformando a Internet. Com avanços como a inteligência artificial e o 5G, ela está ficando ainda mais rápida e inteligente. Porém, isso também significa que precisamos continuar aprendendo sobre como usá-la de forma responsável e segura."
};


export const conteudoLogica = {
    "prim-title": "Lógica",
    "prim-subtitle": "O que é Lógica de Programação?",
    "prim-para-one": "",
    "prim-para-two": "Lógica de programação é como um superpoder para quem quer aprender a programar! É o jeito de pensar e organizar as ideias para resolver problemas e dar instruções para o computador.",
    "prim-para-three": "Pense assim: quando você vai escovar os dentes, segue uma ordem – pega a escova, coloca o creme dental, escova os dentes e enxágua. Isso é lógica! Em programação, fazemos a mesma coisa, só que com passos para o computador seguir.",
    "prim-para-four": "A lógica de programação ensina a gente a planejar, pensar de forma organizada e até criar soluções criativas. Com ela, você pode construir histórias interativas, criar jogos ou até fazer robôs seguirem comandos.",
    "prim-para-five": "",
    "prim-para-six": "Preparado para ativar seu superpoder de lógica? ",
    "prim-para-seven": "",
    "prim-para-eight": "",

    "sec-title": "Lógica",
    "sec-subtitle": "Atividades ???",
    "sec-para-one": "",
    "sec-para-two": "- Atividades desplugadas",
    "sec-para-three": "No contexto da ciência da computação, que é a área que abrange tudo o que envolve programação, as atividades desplugadas são aquelas que podem ser utilizadas para aprender a lógica de programação ou outros temas voltados à computação, mas sem necessariamente precisar do uso de um computador.",
    "sec-para-four": "",
    "sec-para-five": " A vantagem de utilizar atividades desplugadas no aprendizado de lógica de programação é que você pode fazer dele uma vivência que leve as crianças a se divertirem longe das telinhas, através de jogos de tabuleiro e baralho que você pode comprar, como os da Mini Maker Lab, e de outras brincadeiras muito interessantes, como as que estão disponíveis gratuitamente no livro CS Unplugged, de Tim Bell.",
    "sec-para-six": "",
    "sec-para-seven": "",
    "sec-para-eight": "",

    "terc-title": "Lógica",
    "terc-subtitle": "Criatividade",
    "terc-para-one": "",
    "terc-para-two": "Com o ensino de lógica de programação através de atividades desplugadas, também é possível usar a criatividade para criar jogos usando materiais disponíveis em casa, como papelão, tinta e papel, porém será necessário que você realize um estudo prévio do tema antes, para não confundir as crianças com o uso de jogos mal planejados.",
    "terc-para-three": "",
    "terc-para-four": "",
    "terc-para-five": "",
    "terc-para-six": "",
    "terc-para-seven": "",
    "terc-para-eight": "",

    "four-title": "Lógica",
    "four-subtitle": "Jogos de Logica",
    "four-para-one": "Você sabia que dá para aprender programação enquanto joga? Existem jogos superdivertidos que ensinam a lógica de programação de um jeito fácil e colorido!",
    "four-para-two": "",
    "four-para-three": "O Blockly Games, por exemplo, tem vários joguinhos onde você aprende coisas como 'o que é uma variável?'' ou 'como funciona um algoritmo?'. É como resolver desafios enquanto se diverte!",
    "four-para-four": "",
    "four-para-five": "Outro lugar incrível é o Scratch. Nele, você usa blocos, parecidos com peças de LEGO, para criar jogos, histórias e até apresentações! E o melhor: tudo isso enquanto aprende a programar! Você pode usar o Scratch no computador ou direto no site oficial, e é grátis!",
    "four-para-six": "",
    "four-para-seven": "",
    "four-para-eight": "Com essas ferramentas, aprender programação vira uma grande brincadeira. Vamos começar?"
};

export const conteudoProgramacao = {
    "prim-title": "Programação",
    "prim-subtitle": "INTRODUÇÃO",
    "prim-para-one": "",
    "prim-para-two": "Você sabia que os computadores não entendem nossa língua? Eles precisam de instruções especiais para saber o que fazer, e essas instruções são chamadas de programação!",
    "prim-para-three": "Programar é como ensinar um computador a fazer coisas incríveis, como criar jogos, desenhar formas, tocar músicas ou até mesmo ajudar em tarefas importantes, como explorar o espaço!",
    "prim-para-four": "Quando programamos, usamos linguagens que os computadores entendem, como se fossem um alfabeto secreto. Algumas dessas linguagens têm nomes divertidos, como Python, Scratch e JavaScript.",
    "prim-para-five": "",
    "prim-para-six": "E sabe o que é mais legal? Programar é como brincar de resolver enigmas ou montar peças de um quebra-cabeça! Você escreve as instruções, e o computador faz exatamente o que você disse (mesmo se você errar!). Por isso, a programação também ensina a gente a pensar com calma e a resolver problemas de um jeito criativo.",
    "prim-para-seven": "",
    "prim-para-eight": "Se você gosta de tecnologia, aventuras e desafios, aprender a programar pode ser superdivertido. Que tal começar agora? ",

    "sec-title": "Programação",
    "sec-subtitle": "O que é Programação?",
    "sec-para-one": "",
    "sec-para-two": "",
    "sec-para-three": "A programação é a arte de ensinar computadores a fazerem o que queremos. É como falar com eles em uma linguagem especial, chamada linguagem de programação, para dar instruções e criar coisas incríveis, como jogos, aplicativos, sites e até robôs!",
    "sec-para-four": "",
    "sec-para-five": "",
    "sec-para-six": "",
    "sec-para-seven": "",
    "sec-para-eight": "",

    "terc-title": "Programação",
    "terc-subtitle": "Como funciona a programação?",
    "terc-para-one": "Quando programamos, usamos códigos, que são conjuntos de palavras e símbolos que o computador entende. Esses códigos seguem uma lógica e precisam ser escritos com cuidado, porque o computador faz exatamente o que pedimos, nada mais, nada menos.",
    "terc-para-two": "",
    "terc-para-three": "",
    "terc-para-four": "Por exemplo, se você quiser criar um jogo onde um personagem pula, você precisa dizer ao computador algo como:",
    "terc-para-five": "'Se o jogador apertar o botão, o personagem pula.'",
    "terc-para-six": "",
    "terc-para-seven": "",
    "terc-para-eight": "",

    "four-title": "Programação",
    "four-subtitle": "Por que aprender programação?",
    "four-para-one": "Aprender a programar é como desbloquear um superpoder no mundo digital! Veja por quê:",
    "four-para-two": "Criatividade: Você pode transformar suas ideias em realidade.",
    "four-para-three": "Resolver problemas: A programação ensina a pensar de forma lógica e encontrar soluções.",
    "four-para-four": "Oportunidades: No futuro, muitas profissões vão precisar de pessoas que saibam programar.",
    "four-para-five": "Ferramentas legais para começar. Existem ferramentas e jogos que ajudam a aprender programação de forma divertida, como:",
    "four-para-six": "Python: Uma linguagem simples e poderosa para começar a criar projetos maiores.",
    "four-para-seven": "Scratch: Um programa onde você cria histórias e jogos arrastando blocos de código, como peças de LEGO.",
    "four-para-eight": "Blockly: Jogos que ensinam conceitos de programação enquanto você resolve desafios."
};

